"""Consumer/ecosystem-specific compatibility requirements. Profiles do not rewrite facts."""

from refcompat.profiles.ucsc import (
    UcscDatabaseId,
    UcscNameResolution,
    UcscNameResolutionMethod,
    UcscNameResolutionReason,
    UcscNameResolutionState,
    UcscProviderCompleteness,
    UcscProviderContextId,
    UcscProviderDimension,
    UcscProviderSnapshot,
    UcscProviderSource,
    UcscProviderSourceId,
    UcscSequence,
    UcscSequenceAlias,
    UcscTargetBinding,
    UcscTargetBindingId,
    UcscTargetResolution,
    UcscTargetResolutionReason,
    UcscTargetResolutionState,
)
from refcompat.profiles.ucsc_preflight import (
    UCSC_PREFLIGHT_PROFILE_ID,
    UcscPreflightProjection,
    UcscPreflightSequenceProjection,
    UcscPreflightTarget,
    project_ucsc_preflight,
)
from refcompat.profiles.ucsc_reasoning import (
    resolve_ucsc_sequence_name,
    resolve_ucsc_target,
)

__all__ = [
    "UCSC_PREFLIGHT_PROFILE_ID",
    "UcscDatabaseId",
    "UcscNameResolution",
    "UcscNameResolutionMethod",
    "UcscNameResolutionReason",
    "UcscNameResolutionState",
    "UcscPreflightProjection",
    "UcscPreflightSequenceProjection",
    "UcscPreflightTarget",
    "UcscProviderCompleteness",
    "UcscProviderContextId",
    "UcscProviderDimension",
    "UcscProviderSnapshot",
    "UcscProviderSource",
    "UcscProviderSourceId",
    "UcscSequence",
    "UcscSequenceAlias",
    "UcscTargetBinding",
    "UcscTargetBindingId",
    "UcscTargetResolution",
    "UcscTargetResolutionReason",
    "UcscTargetResolutionState",
    "project_ucsc_preflight",
    "resolve_ucsc_sequence_name",
    "resolve_ucsc_target",
]
