"""Consumer/ecosystem-specific compatibility requirements. Profiles do not rewrite facts."""

from refcompat.profiles.ucsc import (
    UcscDatabaseId,
    UcscNameResolution,
    UcscNameResolutionMethod,
    UcscNameResolutionReason,
    UcscNameResolutionState,
    UcscProviderCompleteness,
    UcscProviderContextId,
    UcscProviderDimension,
    UcscProviderSnapshot,
    UcscProviderSource,
    UcscProviderSourceId,
    UcscSequence,
    UcscSequenceAlias,
    UcscTargetBinding,
    UcscTargetBindingId,
    UcscTargetResolution,
    UcscTargetResolutionReason,
    UcscTargetResolutionState,
)
from refcompat.profiles.ucsc_preflight import (
    UCSC_PREFLIGHT_PROFILE_ID,
    UcscPreflightProjection,
    UcscPreflightSequenceProjection,
    UcscPreflightTarget,
    project_ucsc_preflight,
)
from refcompat.profiles.ucsc_reasoning import (
    resolve_ucsc_sequence_name,
    resolve_ucsc_target,
)
from refcompat.profiles.ucsc_snapshot_io import (
    UCSC_PROVIDER_SNAPSHOT_SCHEMA,
    load_ucsc_provider_snapshot,
    parse_ucsc_provider_snapshot,
    render_ucsc_provider_snapshot,
    ucsc_provider_snapshot_sha256,
)

__all__ = [
    "UCSC_PREFLIGHT_PROFILE_ID",
    "UCSC_PROVIDER_SNAPSHOT_SCHEMA",
    "UcscDatabaseId",
    "UcscNameResolution",
    "UcscNameResolutionMethod",
    "UcscNameResolutionReason",
    "UcscNameResolutionState",
    "UcscPreflightProjection",
    "UcscPreflightSequenceProjection",
    "UcscPreflightTarget",
    "UcscProviderCompleteness",
    "UcscProviderContextId",
    "UcscProviderDimension",
    "UcscProviderSnapshot",
    "UcscProviderSource",
    "UcscProviderSourceId",
    "UcscSequence",
    "UcscSequenceAlias",
    "UcscTargetBinding",
    "UcscTargetBindingId",
    "UcscTargetResolution",
    "UcscTargetResolutionReason",
    "UcscTargetResolutionState",
    "load_ucsc_provider_snapshot",
    "parse_ucsc_provider_snapshot",
    "project_ucsc_preflight",
    "render_ucsc_provider_snapshot",
    "resolve_ucsc_sequence_name",
    "resolve_ucsc_target",
    "ucsc_provider_snapshot_sha256",
]
