"""RefCompat-owned immutable domain model.

External library types must not leak into this layer.
"""

from refcompat.model.bundle import BundleReasoningResult
from refcompat.model.conflict_core import (
    ConflictCore,
    ConflictCoreExtraction,
    ConflictCoreId,
    ConflictCoreKind,
)
from refcompat.model.constraints import (
    CompatibilityConstraint,
    ConstraintEvaluation,
    ConstraintId,
    ConstraintRule,
    ConstraintState,
    SatisfactionMode,
)
from refcompat.model.contracts import (
    Capability,
    CapabilityId,
    Requirement,
    RequirementId,
    RequirementLevel,
    RequirementOrigin,
    ResourceContract,
    SequenceIdentityCapability,
    SequenceIdentityRequirement,
    SequenceIdentityValue,
    SequenceLengthCapability,
    SequenceLengthRequirement,
    SequenceOrderCapability,
    SequenceOrderRequirement,
    SequencePresenceCapability,
    SequencePresenceRequirement,
)
from refcompat.model.evaluation import (
    EvaluationPolicyId,
    EvaluationRequest,
    EvaluationScope,
    ProfileId,
)
from refcompat.model.evidence import (
    Evidence,
    EvidenceAggregate,
    EvidenceId,
    EvidenceKind,
    EvidenceMethod,
    EvidencePolarity,
    EvidenceStrength,
)
from refcompat.model.fasta_index import (
    ComputedFastaIndex,
    FastaIndexData,
    FastaIndexDifference,
    FastaIndexDifferenceKind,
    FastaIndexIntegrityResult,
    FastaIndexRecord,
    FastaIndexSnapshot,
)
from refcompat.model.identity import (
    CollectionCompleteness,
    IdentityProviderInfo,
    Md5Digest,
    RefgetSequenceId,
    SeqColAttributeDigest,
    SeqColDigest,
    SequenceCollectionSnapshot,
    SnapshotSequence,
)
from refcompat.model.interpretation import (
    CompatibilityCondition,
    CompatibilityFinding,
    ConditionId,
    ConditionKind,
    FindingId,
    FindingKind,
    InterpretationResult,
)
from refcompat.model.observations import (
    ObservationId,
    ObservationKind,
    ResourceObservation,
    SourceLocation,
)
from refcompat.model.reference_context import (
    ReferenceContext,
    SequenceBinding,
    SequenceBindingId,
    SequenceBindingMethod,
)
from refcompat.model.resources import (
    ArtifactDigest,
    ArtifactDigestAlgorithm,
    ArtifactIdentity,
    Resource,
    ResourceId,
    ResourceKind,
)
from refcompat.model.sequence_dictionary import (
    ExpectedSequenceDictionary,
    MoleculeTopology,
    SequenceDictionaryContentIdentityMatch,
    SequenceDictionaryCrossNameM5LengthInconsistency,
    SequenceDictionaryData,
    SequenceDictionaryDifference,
    SequenceDictionaryDifferenceKind,
    SequenceDictionaryIntegrityResult,
    SequenceDictionaryRecord,
    SequenceDictionarySnapshot,
)
from refcompat.model.vcf import (
    VcfChromUsage,
    VcfContextSnapshot,
    VcfContigDeclaration,
    VcfHeaderData,
)
from refcompat.model.verdict import CompatibilityVerdict, VerdictAggregation

__all__ = [
    "ArtifactDigest",
    "ArtifactDigestAlgorithm",
    "ArtifactIdentity",
    "BundleReasoningResult",
    "Capability",
    "CapabilityId",
    "CollectionCompleteness",
    "CompatibilityCondition",
    "CompatibilityConstraint",
    "CompatibilityFinding",
    "CompatibilityVerdict",
    "ComputedFastaIndex",
    "ConditionId",
    "ConditionKind",
    "ConflictCore",
    "ConflictCoreExtraction",
    "ConflictCoreId",
    "ConflictCoreKind",
    "ConstraintEvaluation",
    "ConstraintId",
    "ConstraintRule",
    "ConstraintState",
    "EvaluationPolicyId",
    "EvaluationRequest",
    "EvaluationScope",
    "Evidence",
    "EvidenceAggregate",
    "EvidenceId",
    "EvidenceKind",
    "EvidenceMethod",
    "EvidencePolarity",
    "EvidenceStrength",
    "ExpectedSequenceDictionary",
    "FastaIndexData",
    "FastaIndexDifference",
    "FastaIndexDifferenceKind",
    "FastaIndexIntegrityResult",
    "FastaIndexRecord",
    "FastaIndexSnapshot",
    "FindingId",
    "FindingKind",
    "IdentityProviderInfo",
    "InterpretationResult",
    "Md5Digest",
    "MoleculeTopology",
    "ObservationId",
    "ObservationKind",
    "ProfileId",
    "ReferenceContext",
    "RefgetSequenceId",
    "Requirement",
    "RequirementId",
    "RequirementLevel",
    "RequirementOrigin",
    "Resource",
    "ResourceContract",
    "ResourceId",
    "ResourceKind",
    "ResourceObservation",
    "SatisfactionMode",
    "SeqColAttributeDigest",
    "SeqColDigest",
    "SequenceBinding",
    "SequenceBindingId",
    "SequenceBindingMethod",
    "SequenceCollectionSnapshot",
    "SequenceDictionaryContentIdentityMatch",
    "SequenceDictionaryCrossNameM5LengthInconsistency",
    "SequenceDictionaryData",
    "SequenceDictionaryDifference",
    "SequenceDictionaryDifferenceKind",
    "SequenceDictionaryIntegrityResult",
    "SequenceDictionaryRecord",
    "SequenceDictionarySnapshot",
    "SequenceIdentityCapability",
    "SequenceIdentityRequirement",
    "SequenceIdentityValue",
    "SequenceLengthCapability",
    "SequenceLengthRequirement",
    "SequenceOrderCapability",
    "SequenceOrderRequirement",
    "SequencePresenceCapability",
    "SequencePresenceRequirement",
    "SnapshotSequence",
    "SourceLocation",
    "VcfChromUsage",
    "VcfContextSnapshot",
    "VcfContigDeclaration",
    "VcfHeaderData",
    "VerdictAggregation",
]
