"""Format-specific observation extraction."""

from refcompat.inspectors.alignment import (
    AlignmentInspectionError,
    AlignmentParseError,
    AlignmentProviderIncompatibleError,
    AlignmentUnreadableError,
    UnsupportedAlignmentResourceError,
    inspect_alignment_header,
)
from refcompat.inspectors.fasta_index import (
    FastaIndexComputationError,
    FastaIndexError,
    FastaIndexParseError,
    FastaIndexProviderIncompatibleError,
    FastaIndexUnreadableError,
    UnsupportedFastaIndexRepresentationError,
    UnsupportedFastaIndexResourceError,
    compute_expected_fasta_index,
    read_fasta_index,
)
from refcompat.inspectors.fasta_sequence import (
    FastaSequenceAccessError,
    FastaSequenceFetchError,
    FastaSequenceProviderIncompatibleError,
    PysamFastaSequenceReader,
    UnsupportedFastaSequenceResourceError,
    open_fasta_sequence_reader,
)
from refcompat.inspectors.sequence_dictionary import (
    SequenceDictionaryComputationError,
    SequenceDictionaryError,
    SequenceDictionaryParseError,
    SequenceDictionaryUnreadableError,
    UnsupportedSequenceDictionaryResourceError,
    expected_sequence_dictionary_from_snapshot,
    read_sequence_dictionary,
)
from refcompat.inspectors.vcf import (
    UnsupportedVcfResourceError,
    VcfInspectionError,
    VcfParseError,
    VcfProviderIncompatibleError,
    VcfUnreadableError,
    inspect_vcf_context,
    iter_vcf_ref_records,
)

__all__ = [
    "AlignmentInspectionError",
    "AlignmentParseError",
    "AlignmentProviderIncompatibleError",
    "AlignmentUnreadableError",
    "FastaIndexComputationError",
    "FastaIndexError",
    "FastaIndexParseError",
    "FastaIndexProviderIncompatibleError",
    "FastaIndexUnreadableError",
    "FastaSequenceAccessError",
    "FastaSequenceFetchError",
    "FastaSequenceProviderIncompatibleError",
    "PysamFastaSequenceReader",
    "SequenceDictionaryComputationError",
    "SequenceDictionaryError",
    "SequenceDictionaryParseError",
    "SequenceDictionaryUnreadableError",
    "UnsupportedAlignmentResourceError",
    "UnsupportedFastaIndexRepresentationError",
    "UnsupportedFastaIndexResourceError",
    "UnsupportedFastaSequenceResourceError",
    "UnsupportedSequenceDictionaryResourceError",
    "UnsupportedVcfResourceError",
    "VcfInspectionError",
    "VcfParseError",
    "VcfProviderIncompatibleError",
    "VcfUnreadableError",
    "compute_expected_fasta_index",
    "expected_sequence_dictionary_from_snapshot",
    "inspect_alignment_header",
    "inspect_vcf_context",
    "iter_vcf_ref_records",
    "open_fasta_sequence_reader",
    "read_fasta_index",
    "read_sequence_dictionary",
]
